import { StyleSheet } from 'react-native';
import COLOR, { colors } from './color';
import text from './text';
import common from './common';

const BASIC_SHADOW = {
  borderRadius: 8,
  shadowColor: colors.black,
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.2,
  shadowRadius: 1,
  elevation: 1,
};

export default StyleSheet.create({
  loan: {
    ...text.blackBodyReg,
    ...COLOR.bgWhite,
    width: '80%',
    padding: 8,
    ...BASIC_SHADOW,
  },
  input: {
    ...text.blackTitleScreen,
    ...COLOR.bgWhite,
    // padding: 16,
    marginTop: 4,
    ...BASIC_SHADOW,
    borderColor: colors.lightestGrey,
    borderWidth: 1,
    width: '100%',
    height: 50,
    lineHeight: 20,
    justifyContent: 'center',
    padding: 10,
  },
  inputInvalid: {
    ...BASIC_SHADOW,
    ...text.blackTitleScreen,
    ...COLOR.bgWhite,
    padding: 16,
    marginTop: 4,
    borderColor: colors.baseRed,
    borderWidth: 0.5,
    width: '100%',
    height: 50,
    lineHeight: 20,
  },
  inputRow70: {
    ...BASIC_SHADOW,
    ...text.blackTitleScreen,
    ...COLOR.bgWhite,
    marginTop: 4,
    borderColor: colors.lightestGrey,
    borderWidth: 1,
    width: '55%',
    height: 50,
    lineHeight: 20,
    justifyContent: 'center',
    padding: 10,
  },
  inputRow20: {
    ...BASIC_SHADOW,
    ...text.blackTitleScreen,
    ...COLOR.bgWhite,
    marginTop: 4,
    borderColor: colors.lightestGrey,
    borderWidth: 1,
    width: '25%',
    height: 50,
    lineHeight: 20,
    justifyContent: 'center',
    padding: 10,
  },
  inputRow70Disable: {
    ...BASIC_SHADOW,
    ...text.blackTitleScreen,
    ...COLOR.bgLightestGrey,
    borderColor: colors.lightestGrey,
    borderWidth: 1,
    width: '55%',
    height: 50,
    lineHeight: 20,
    justifyContent: 'center',
    padding: 10,
  },
  inputRow20Disable: {
    ...BASIC_SHADOW,
    ...text.blackTitleScreen,
    ...COLOR.bgLightestGrey,
    borderColor: colors.lightestGrey,
    borderWidth: 1,
    width: '25%',
    height: 50,
    lineHeight: 20,
    justifyContent: 'center',
    padding: 10,
  },
  inputRow50: {
    ...COLOR.bgWhite,
    ...BASIC_SHADOW,
    width: '50%',
    ...common.centerVertically,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  picker: {
    ...COLOR.bgWhite,
    ...BASIC_SHADOW,
  },
  promo: {
    ...text.greyLabelText,
    width: '80%',
  },
  imageBlank: {
    borderRadius: 8,
    // shadowColor: colors.black,
    // shadowOffset: { width: 0, height: 1 },
    // shadowOpacity: 0.2,
    // shadowRadius: 1,
    // elevation: 1,
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: colors.lightestGrey,
    borderStyle: 'dashed',
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
